# Use an official Python runtime as a parent image ...
FROM python:3.9.0

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy sample_config.py to config.py
RUN cp sample_config.py config.py

# Run bot.py when the container launches
CMD ["python", "bot.py"]
